# Generated by Django 5.2.5 on 2025-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddoc',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
